version: '2'
services:
    web:
        build: .
        command: python3 app/runserver.py
        volumes:
            - .:/usr/src/app
        ports:
            - "5001:5001"
        depends_on:
            - db
    db:
        image: mysql:5.7
        volumes:
            - .:/usr/src/db
        ports:
          - "3306:3306"
        environment:
          MYSQL_DATABASE: "engineering"
          MYSQL_ROOT_PASSWORD: "password"